---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "Aidan Pfunder"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Project Notes

__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

My name "Aidan" was not used very often before my birth year of 2001, but shot up in popularity in the early 2000s. 

```{python}
# Include and execute your code here

aidan = df[df['name'] == 'Aidan']

ggplot(aidan, aes(x='year', y='Total')) + \
geom_line(color='blue') + \
geom_vline(xintercept=2001, color="red", linetype="dashed") + \
scale_x_continuous(format="d") + \
ggtitle("The name 'Aidan' Over Time")
 




```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

If I talked to someone named Brittany on the phone, I would guess she was born in 1990, making her 35 years old. Based on the graph, I would not guess that she is older than 45 or younger than 25.

```{python}
# Include and execute your code here

brittany = df[df['name'] == 'Brittany']

ggplot(brittany, aes(x='year', y='Total')) + \
geom_line(color='blue') + \
scale_x_continuous(format="d") + \
ggtitle("Name Usage Over Time for 'Brittany'") + \
xlab("Year") + ylab("Total Names")  




```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

Mary was the most popular of the 4 names. All 4 names dropped in popularity over time, but Mary dropped the most.

```{python}
names = df[df["name"].isin(["Mary", "Martha", "Peter", "Paul"])]

names = names[(names["year"] >= 1920) & (names["year"] <= 2000)]

(ggplot(names, aes(x="year", y="Total", color="name")) + \
 geom_line(size=1.2) + \
 scale_x_continuous(format="d") + \
 ggtitle("Trends of Mary, Martha, Peter, and Pau(1920–2000)") + \
 xlab("Year") + ylab("Total Names")) 



```



## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

This graph shows that the name "Tony" was at its' most popular around 1960, with a sharp decline afterward. I thought the relase of Iron Man in 2008 would have some effect; however, it seems it changed nothing and the name continued to drop in popularity after the movie.

```{python}
tony = df[df["name"] == "Tony"]

(ggplot(tony, aes(x="year", y="Total")) + \
 geom_line(color="red") + \
 geom_vline(xintercept=2008, color="black", linetype="dashed") + \
 scale_x_continuous(format="d") + \
 ggtitle("Did Iron Man Boost the Name 'Tony'?") + \
 xlab("Year") + \
 ylab("Total Named Tony")) 





```

---

## STRETCH QUESTION|TASK 1

__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

The name Elliot seemed to lose popularity after the release of the first E.T. It gained popularity after the second release, fell back down, and then really started to rise in 2000 at the third release. It is difficult to deteermine if the movie releases contribute to the name's popularity because it seems to rise and fall independent of the movie releases.

```{python}

elliot = df[df["name"] == "Elliot"].copy()
elliot["label"] = "Elliot" 

annotations = pd.DataFrame({
    "year": [1981, 1986, 2003], 
    "Total": [1250, 1250, 1250],
    "label": ["E.T Released", "Second", "Third"],
    "hjust": [1, 0, 0]  
})

plot = (
    ggplot(elliot, aes(x="year", y="Total", color="label")) +
    geom_line(size=1.2, alpha=0.7) +

    geom_vline(xintercept=1982, color="red", linetype="dashed", size=1) +
    geom_vline(xintercept=1985, color="red", linetype="dashed", size=1) +
    geom_vline(xintercept=2002, color="red", linetype="dashed", size=1) +

    geom_text(
        data=annotations,
        mapping=aes(x="year", y="Total", label="label", hjust="hjust"),
        color="black", size=7
    ) +

    scale_color_manual(values={"Elliot": "blue"}) +
    scale_x_continuous(format="d") +
    ggtitle("Elliot... What?") +
    xlab("year") + ylab("Total")
)

plot




```


---
